---
# Python 3 support
pip_virtualenv_command: /usr/bin/python3 -m venv  # usegalaxy_eu.certbot, usegalaxy_eu.tiaas2, galaxyproject.galaxy
certbot_virtualenv_package_name: python3-venv     # usegalaxy_eu.certbot

# Common variables needed by all hosts
galaxy_user_name: galaxy
galaxy_db_name: galaxy

cvmfs_role: client
galaxy_cvmfs_repos_enabled: config-repo
cvmfs_quota_limit: 500

# Galaxy vars that will be reused by Pulsar
galaxy_job_metrics_plugins:
  - type: core
  - type: cpuinfo
  - type: meminfo
  - type: uname
  - type: env
  - type: cgroup
  - type: hostname
